steps:
  # Deploy to Cloud Run directly from source
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'fake-news-detector-api'
      - '--source'
      - '.'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '12'
      - '--concurrency'
      - '80'
      - '--port'
      - '8080'

options:
  logging: CLOUD_LOGGING_ONLY
